import {Location} from './location.model';
import {Genre} from './genre.model';
import {Role} from './role.model';
import {Video} from './video.model';
import {Track} from './track.model';


export interface Directory {
  agent?: string;
  allowSync?: string;
  art?: string;
  composite?: string;
  content?: string;
  contentChangedAt?: string;
  createdAt?: string;
  directory?: string;
  directoryId?: number;
  filters?: string;
  key?: string;
  secondary?: string;
  prompt?: string;
  search?: string;
  language?: string;
  location?: Location;
  refreshing?: string;
  scannedAt?: string;
  scanner?: string;
  thumb?: string;
  title?: string;
  type?: string;
  updatedAt?: string;
  uuid?: string;
  summary?: string;
  banner?: string;
  genre?: Genre[];
  roles?: Role[];
  videos?: Video[];
  childCount?: string;
  year?: number;
  rating?: number;
  leafCount?: number;
  viewedLeafCount?: number;
  transcodedPhoto?: string;
  addedAt?: string;
  index?: string;
  ratingKey?: string;
  guid?: string;
  studio?: string;
  librarySectionID?: string;
  Director?: string;
  originallyAvailableAt?: string;
  parentTitle?: string;
  parentThumb?: string;
  librarySectionUUID?: string;
  parentKey?: string;
  librarySectionTitle?: string;
  parentGuid?: string;
  track?: Track[];
}
